SET
    search_path TO public;

BEGIN WORK;

SET
    TRANSACTION READ WRITE;

SET
    datestyle = DMY;

CREATE TABLE Categories (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "image" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY(id)
);

CREATE TABLE Users (
    "id" UUID NOT NULL,
    "firstName" VARCHAR(255) NOT NULL,
    "lastName" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY(id)
);

CREATE TABLE Orders (
    "id" UUID NOT NULL,
    "firstName" VARCHAR(255) NOT NULL,
    "lastName" VARCHAR(255) NOT NULL,
    "address" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "city" VARCHAR(255) NOT NULL,
    "postalCode" VARCHAR(255) NOT NULL,
    "country" VARCHAR(255) NOT NULL,
    "id_user" UUID NOT NULL,
    CONSTRAINT PK_ORDER PRIMARY KEY(id),
    CONSTRAINT FK_USER_ORDER FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE Products (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "price" DECIMAL NOT NULL,
    "image" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "id_category" UUID NOT NULL,
    CONSTRAINT FK_CATEGORY_PRODUCT FOREIGN KEY(id_category) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY(id)
);

CREATE TABLE OrderProducts (
    "id_order" UUID,
    "id_product" UUID,
    "quantity" smallint NOT NULL,
    CONSTRAINT PK_ORDER_PRODUCTS PRIMARY KEY (id_order, id_product),
    CONSTRAINT FK_ORDER_ORDER_PRODUCT FOREIGN KEY(id_order) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PRODUCT_ORDER_PRODUCT FOREIGN KEY(id_product) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;
